drone0:
  agent:
    ros__parameters:
      drone_id: 0
      group_id: 0

drone1:
  agent:
    ros__parameters:
      drone_id: 1
      group_id: 0

drone2:
  agent:
    ros__parameters:
      drone_id: 2
      group_id: 1

drone3:
  agent:
    ros__parameters:
      drone_id: 3
      group_id: 1